config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,
             controllers: { omniauth_callbacks: 'customers/omniauth_callbacks' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :customers, except: [:index] do
    resources :contacts, only: %i[new create]

  end
  resources :contacts, only: %i[index edit update destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer

  validates :name, :cellphone, :emails, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include PgSearch::Model

  pg_search_scope :search_by_name_and_email,
                  against: %i[name email],
                  using: {
                    tsearch: { prefix: true }
                  }
  validates :email, presence: true

  has_many :contacts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    customer_params = auth.slice('provider', 'uid')
    customer_params.merge! auth.info.slice('email', 'first_name', 'last_name')
    customer_params[:facebook_picture_url] = auth.info.image
    customer_params[:token] = auth.credentials.token
    customer_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    customer_params = customer_params.to_h

    customer = Customer.find_by(provider: auth.provider, uid: auth.uid)
    customer ||= Customer.find_by(email: auth.info.email) # Customer did a regular sign up in the past.
    if customer
      customer.update(customer_params)
    else
      customer = Customer.new(customer_params)
      customer.password = Devise.friendly_token[0, 20]  # Fake password for validation
      customer.save
    end

    customer
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]
  #before_action :set_customer

  def index
  @contacts = Contact.all
  end 
  
  def new
  # we need @customer in our `simple_form_for`
    @customer = Customer.find(params[:customer_id])
    @contact = Contact.new
  end

  def show
    
  end
  
  def edit
    
    
  end
  
  def update

    if @contact.update(contact_params)
      redirect_to contacts_path, notice: 'contact was successfully updated.'
    else
      render :edit
    end
    

  end  
  
  
  def create
    @contact = Contact.new(contact_params)
    # we need `customer_id` to associate contact with corresponding customer
    @customer = Customer.find(params[:customer_id])
    @contact.customer = @customer
    if @contact.save
    redirect_to customer_path(@customer)
    else
    render :new
    end
  end
  
  def destroy
  @contact.destroy
  redirect_to customer_path(@contact.customer)
  end
  
  private
  
  def set_contact
  @contact = Contact.find(params[:id])
  end

  
  def contact_params
  params.require(:contact).permit(:name, :emails, :cellphone)
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    customer = Customer.find_for_facebook_oauth(request.env['omniauth.auth'])

    if customer.persisted?
      sign_in_and_redirect customer, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to customer_facebook_omniauth_callback
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  def new
    @customer = Customer.new
    
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @customer.update(customer_params)

    redirect_to customer_path, notice: 'customer was successfully updated.'
  end

  def destroy
    @customer.destroy
    redirect_to root_path, notice: 'customer was successfully destroyed.'
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :telephone, :email, :register_day)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @customers = Customer.all

    @customers = if params[:query].present?
                   Customer.search_by_name_and_email(params[:query])
                 else
                   Customer.all
                 end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for ([@customer,@contact]) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :emails %>
    <%= f.input :cellphone %>
  </div>

  <div class="form-actions">
     <%= f.submit "add/edit a contact", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="container">
<h1>edit a Contact</h1>
<%= render 'form', contact: @contact %>
</div>

app/views/contacts/index.html.erb
<ul>
  <% @contacts.each do |contact| %>
    <li><%= link_to contact.name, customer_path(contact) %></li>
  <% end %>
</ul>

  <%= link_to 'Back to HomePage', root_path , class:'btn btn-secondary' %>

app/views/contacts/new.html.erb
<div class="container">
<h1>Create a Contact</h1>
<%= render 'form', customer: @customer, contact: @contact %>
</div>

app/views/customers/_form.html.erb
<%= simple_form_for(customer) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :telephone %>
  <%= f.input :register_day %>
  <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<%= render "form", customer: @customer %>

app/views/customers/index.html.erb
<ul>
  <% @customers.each do |customer| %>
    <li><%= link_to customer.name, customer_path(customer) %></li>
  <% end %>
</ul>

app/views/customers/new.html.erb
<%= render "form", customer: @customer %>

app/views/customers/show.html.erb
 <div class="customer-name">
  <h1><%= @customer.name %></h1>

  <h2>Telephone</h2>
  <p><%= @customer.telephone %></p>
  <p><%= @customer.email %></p>

  <h3>Register Day</h3>
  <p><%= @customer.register_day %></p>
  
  <%= link_to edit_customer_path(@customer) do %>
   Edit Customer <i class="far fa-edit"></i>
  <% end %>
 
</div>

   
<div class="crud-customer">

  <%= link_to "Delete #{@customer.name}",
              customer_path(@customer),
              method: :delete,
              data: { confirm: "Are you sure?" } , class:'btn btn-warning'%>
              

                            <i class="fas fa-trash"></i>
</div>
<div class="create-card">
          <%= link_to 'Create more contacts', new_customer_contact_path(@customer), class:'btn btn-success'  %>
  <i class="fas fa-plus"></i>
</div>
                
</div>

<div class="remove-card">

    <div class="cards-contact">
      <div class="card" style="width: 18rem;">
        <% @customer.contacts.each do |contact| %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= contact.name  %></li>   
          <li class="list-group-item"><%= contact.cellphone %></li>
          <li class="list-group-item"><%= contact.emails %></li>
        </ul>

         

    <%= link_to edit_contact_path(contact) do %>
      Edit Contacts <i class="far fa-edit"></i>
    <% end %>

      <%= link_to "Remove",
                  contact_path(contact),
                  data: { confirm: "Are you sure?" } %>
                   <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>

    

  
      
      

    

  <%= link_to 'Back to HomePage', root_path , class:'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerXCx</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>



  </body>
</html>

app/views/pages/home.html.erb
<p>
  <span id="banner-typed-text"></span>
</p>


<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group" id='search-bar'>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a Name"
  %>
  <%#= submit_tag "Search", class: "btn btn-primary" %>
  <button name="button" type="submit" class="btn btn-flat">
    <i class="fas fa-search"></i> Search
  </button>

  </div>
<% end %>
<ul>
  <% @customers.each do |customer| %>
    <li><%= link_to customer.name, customer_path(customer) %></li>
  <% end %>
</ul>



<%= link_to 'Get a list from all contacts', contacts_path , class:'btn btn-outline-dark' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/marisnner7"><i class="fab fa-github"></i></a>
    <a href="http://www.linkedin.com/in/marianne-aguiar-dev"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by <a href="https://www.marianneag.dev/">Marianne</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


      <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if customer_signed_in? %>
       
        <li class="nav-item">
          <%= link_to "Log out", destroy_customer_session_path, method: :delete, class: "dropdown-item" %>
        </li>
        <li class="nav-item dropdown">
          <% avatar_url = current_customer.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_customer_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>